# Generated by Django 3.1.7 on 2021-03-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacao',
            name='publico',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
